---
nav:
  - platorm_refresh_updates.md
  - Preparing_to_move_data_to_NeSI_long_term_storage.md
  - Preparing_your_code_for_use_on_NeSIs_new_HPC_platform.md
  - Accessing_NeSI_Support_during_the_holiday_break.md
  - Improved_data_management_and_efficient_use_of_NeSI_HPC_storage.md
