nav:
 - Hardware.md
 - Job_prioritisation.md
 - SLURM-Best_Practice.md
 - Using_GPUs.md
 - Job_Checkpointing.md
 - Slurm_Interactive_Sessions.md
 - Fair_Share.md
 - Checksums.md
 - Checking_your_projects_usage_using_nn_corehour_usage.md
 - ...
