matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - docs/assets/glossary/dictionary.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      escapes: '\\[\\`~]'
      delimiters:
      # Ignore multiline content between fences
      # ```md
      # content
      # ```
      - open: '(?s)^(?P<open> *`{3}\s?[a-zA-Z]*)$'
        close: '^(`{3})$'
      # Ignore the content in meta
      # ---
      # content
      # ---
      - open: '(?s)^(?P<open> *-{3})$'
        close: '^(?P=open)$'    
      # Ignore content between inline back ticks
      #  `content`
      - open: '(?P<open>`+)'
        close: '(?P=open)'
      # Ignore content in page links
      #  [some page](../link/to/some/page.md)
      - open: '(\]\()'
        close: '(\))'
      # Ignore macros
      # {{some.template.variable}}
      - open: '(\{\{)'
        close: '(\}\})'
      # Ignore include
      # {% include "partials/support_request.html" %}
      - open: '({%)'
        close: '(%})'
  - pyspelling.filters.url:
  - pyspelling.filters.markdown:
      markdown_extensions:
      # - markdown.extensions.toc
      - markdown.extensions.admonition
      - markdown.extensions.attr_list
      - markdown.extensions.abbr
      - markdown.extensions.tables  
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'docs/**/*.md'
  default_encoding: utf-8
