nav:
  - Storage_best_practices.md
  - File_Systems_and_Quotas
  - Data_Recovery
  - Long_Term_Storage
  - Cloud_Storage
  - Moving_files_to_and_from_the_cluster.md
  - FileSender.md
  - Globus
  - "*"
