nav:
 - OpenMP_settings.md
 - Offloading_to_GPU_with_OpenMP.md
 - Offloading_to_GPU_with_OpenACC.md
 - NVIDIA_GPU_Containers.md
 - Configuring_Dask_MPI_jobs.md
 - Software_Version_Management.md
 - Thread_Placement_and_Thread_Affinity.md
 - Installing_Third_Party_applications.md
 - Compiling_software_on_Mahuika.md
 - ...
