nav:
 - Build_an_Apptainer_container_on_a_Milan_compute_node.md
 - OpenMP_settings.md
 - Offloading_to_GPU_with_OpenMP.md
 - Offloading_to_GPU_with_OpenACC.md
 - NVIDIA_GPU_Containers.md
 - Configuring_Dask_MPI_jobs.md
 - Software_Version_Management.md
 - Thread_Placement_and_Thread_Affinity.md
 - NICE_DCV_Setup.md
 - Visualisation_software.md
 - Finding_Software.md
 - Installing_Third_Party_applications.md
 - Compiling_software_on_Mahuika.md
 - Compiling_software_on_Maui.md
 - Programming_environment_differences_between_Maui_and_Mahuika.md
 - ...