---
nav:
  - Overview.md
  - First_Time_Setup.md
  - Add_Your_Computer_To_Globus.md
  - Data_Transfer_using_Globus.md
  - Data_Transfer_Between_Personal_Endpoints.md
  - Bookmarks.md
  - Share_Collections.md
  - Globus_CLI.md
  - Globus_Cheetsheet.md
