nav:
  - Supported_Applications
  - Training
  - Interactive_computing_with_OnDemand
  - Batch_Jobs
  - Profiling_and_Debugging
  - HPC_Software_Environment
  - Terminal_Setup
  - Research_Developer_Cloud
  - "*"
