nav:
  - Supported_Applications
  - Training
  - Interactive_computing_using_Jupyter
  - The_NeSI_High_Performance_Computers
  - Running Jobs on Māui and Mahuika: Running_Jobs_on_Maui_and_Mahuika
  - Profiling_and_Debugging
  - HPC_Software_Environment
  - Terminal_Setup
  - Manuals_and_User_Guides
  - Release Notes jupyter.nesi.org.nz: Release_Notes_jupyter-nesi-org-nz