---
[
    ".core",
    "2fa",
    "Computational Chemistry",
    "Density Functional Theory",
    "Molecular Dynamics",
    "Slurm",
    "XC50",
    "access",
    "account",
    "allocation",
    "announcement",
    "assessment",
    "authentication",
    "bash",
    "biology",
    "cae",
    "cfd",
    "chemistry",
    "compiler",
    "compression",
    "containers",
    "corefile",
    "CS400",
    "CS500",
    "data compression",
    "disk quota",
    "earthquake",
    "engineering",
    "fea",
    "geo",
    "git",
    "github",
    "globus",
    "gpu",
    "home",
    "hydrodynamics",
    "ide",
    "introduction",
    "jupyter lab",
    "login",
    "mahuika",
    "maui",
    "mfa",
    "milan",
    "machine learning",
    "morphodynamics",
    "mpi",
    "multiphysics",
    "mynesi",
    "nearline",
    "nobackup",
    "omp",
    "onboarding",
    "ondemand",
    "particle modelling",
    "profiling",
    "project",
    "quotas",
    "refresh",
    "releasenote",
    "Project Membership",
    "scaling",
    "scp",
    "software",
    "ssh",
    "storage",
    "tape",
    "terminal",
    "toolchain",
    "Data Transfer",
    "tuakiri",
    "upload",
    "version control",
    "visualisation",
    "water quality testing",
    "wave modelling",
    "webinar",
    "windows",
    "workshop",
    "wsl",
    "x11",
]
