---
[
    "Chemistry", 
    "DensityFunctionalTheory",
    "MolecularDynamics",
    "Slurm",
    "access",
    "account",  # Any page relating to user account
    "allocation", 
    "biology",
    "cae",
    "cfd",
    "chemistry",
    "compiler",
    "containers",
    "diskQuota",
    "earthquake",
    "engineering",
    "fea",
    "geo",
    "gpu",
    "hydrodynamics",
    "ide",
    "jupyter",
    "login",
    "machineLearning",
    "morphodynamics",
    "mpi",
    "multiphysics",
    "mynesi",
    "nobackup",
    "multiproccessing",
    "ondemand",
    "particleModelling",
    "profiling",
    "project",
    "releasenote",
    "ssh",
    "storage",
    "DataTransfer",
    "visualisation",
    "waveModelling",
    "windows",
]
