---
nav:
- jupyter-nesi-org-nz_release_notes_27-08-2024.md
- jupyter-nesi-org-nz_release_notes_30-07-2024.md
- jupyter-nesi-org-nz_release_notes_26-03-2024.md
- jupyter-nesi-org-nz_release_notes_22-11-2023.md
- jupyter-nesi-org-nz_release_notes_14-11-2023.md
- jupyter-nesi-org-nz_release_notes_15-06-2023.md
- jupyter-nesi-org-nz_release_notes_19-05-2023.md
- jupyter-nesi-org-nz_release_notes_02-02-2023.md
- jupyter-nesi-org-nz_release_notes_25-08-2022.md
- jupyter-nesi-org-nz_release_notes_12-07-2022.md
- jupyter-nesi-org-nz_release_notes_31-03-2022.md
- jupyter-nesi-org-nz_release_notes_28-06-2022.md
- jupyter-nesi-org-nz_release_notes_02-06-2022.md
- jupyter-nesi-org-nz_release_notes_02-11-2021.md
- jupyter-nesi-org-nz_release_notes_14-10-2021.md
- jupyter-nesi-org-nz_release_notes_24-09-2021.md
- jupyter-nesi-org-nz_release_notes_16-09-2021.md
- jupyter-nesi-org-nz_release_notes_12-05-2021.md
