name: automerge
env:
  GH_TOKEN: ${{ github.token }}
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  automerge:
    if: ${{ github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        gh pr checks $GITHUB_HEAD_REF --watch --fail-fast --required
        # gh run view --json number $GITHUB_HEAD_REF
        gh pr merge $GITHUB_HEAD_REF --squash --auto --delete-branch


