name: Merge Schedule
on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types:
      - opened
      - edited
  schedule:
    - cron: '0 * * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: squash
          # Time zone to use. Default is UTC.
          # time_zone: 'Pacific/Auckland'
          require_statuses_success: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

